In [10]:
import numpy as np 
import torch

## a) generate X

In [11]:
X = np.random.randn(100,200)
X.shape,X.ndim, X

((100, 200),
 2,
 array([[ 0.75821533, -0.48881008,  0.05085505, ..., -0.71834822,
         -0.32417226,  0.19765978],
        [ 1.18715933,  0.68149295, -1.69432004, ...,  0.23115223,
         -0.42426234, -1.20053989],
        [ 0.40687363, -1.85159556,  0.64354665, ..., -0.71777916,
          0.55448003, -0.110387  ],
        ...,
        [ 0.6955354 ,  1.74034233,  0.61635913, ..., -0.39979527,
          2.29582673,  0.45238081],
        [ 1.05493573,  1.26369394, -1.11692905, ..., -0.80737157,
          0.24558324, -0.22415105],
        [ 1.30674381,  1.12902834,  0.25860154, ...,  1.43645306,
          0.81363473, -1.5376071 ]], shape=(100, 200)))

## Shapes

#### Layer 1

z1 = W1 @ x + b1

[20,1] = [20,200]@[200,1] + [20,1]

### Layer 2
z2 = W2 @ a1 + b2

[10,1] = [10,20]@[20,1] + [10,1]


### for 100 examples

#### Layer 1

z1 = W1 @ x + b1

[20,100] = [20,200]@[200,100] + [20,1]

### Layer 2

z2 = W2 @ a1 + b2

[10,100] = [10,20]@[20,100] + [10,1]

## b) generate labels

In [12]:
labels = np.random.randint(0,10,(100,))
labels

array([7, 0, 3, 7, 5, 7, 7, 0, 6, 8, 3, 3, 6, 1, 7, 0, 7, 3, 5, 5, 7, 2,
       1, 5, 9, 4, 1, 5, 6, 0, 7, 3, 0, 0, 9, 4, 2, 0, 3, 1, 4, 2, 2, 3,
       6, 0, 3, 8, 3, 2, 0, 7, 8, 6, 9, 9, 7, 4, 1, 6, 6, 0, 2, 1, 0, 9,
       4, 5, 5, 6, 2, 5, 5, 1, 4, 8, 4, 3, 2, 3, 2, 7, 7, 1, 9, 8, 3, 7,
       1, 3, 7, 1, 6, 1, 6, 5, 0, 3, 4, 3], dtype=int32)

In [13]:
y = np.zeros((100,10))
y.shape,y.ndim

((100, 10), 2)

In [14]:
y[np.arange(100),labels] = 1
y

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 

## d) generate weights and biases

In [23]:
"""#### Layer 1

z1 = W1 @ x + b1

[20,100] = [20,200]@[200,100] + [20,1]

### Layer 2

z2 = W2 @ a1 + b2

[10,100] = [10,20]@[20,100] + [10,1]"""
W1 = np.random.randn(20,200)
b1 = np.random.randn(20,1)
W2 = np.random.randn(10,20)
b2 = np.random.randn(10,1)
W1.shape, b1.shape, W2.shape, b2.shape

((20, 200), (20, 1), (10, 20), (10, 1))

## c) implement nn in python

In [ ]:
def forward(x):
    z1 = W1@x + b1
    a1 = np.tanh(z1)
    z2 = W2@a1 + b2
    return z2

> z2 = [10,100]

> labels = [100,1]

> X = [100,200], we have to transpose it

In [18]:
X.shape

(100, 200)

In [19]:
X = X.T
X.shape

(200, 100)

In [28]:
output = forward(X)
output.shape

(10, 100)

In [35]:
y_pred = output.T
y_pred.shape # out task is to apply softmax on this

(100, 10)

In [41]:
def softmax(x):
    x_shifted = x - np.max(x, axis=1, keepdims=True)
    exp_x = np.exp(x_shifted)
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

# Example
y_out = softmax(y_pred)
y_out.shape

(100, 10)

In [42]:
row_sums = np.sum(y_out, axis=1)
print(row_sums)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


y_out = [100,10] , by doint transpose of output then applying softmax

[12,2,3,4,54,12,4,7,87,9]
[]
[].
.
.
.

----->(softmax)


[0,0,0.1,0.5,0.2,0,0.2,0,0,0]  ==> sum=1
[]
[].
.
.
.



## e) calculate loss

In [47]:
pred_classes = np.argmax(y_out, axis=1)
pred_classes

array([1, 2, 9, 7, 4, 4, 4, 4, 4, 8, 9, 9, 8, 4, 5, 8, 9, 9, 3, 4, 4, 2,
       3, 1, 4, 3, 3, 0, 2, 9, 3, 2, 3, 8, 9, 7, 9, 6, 3, 2, 9, 6, 2, 0,
       6, 2, 9, 4, 3, 9, 9, 0, 4, 0, 9, 9, 4, 3, 4, 3, 3, 3, 4, 3, 3, 8,
       8, 9, 0, 4, 9, 6, 8, 6, 9, 0, 8, 9, 3, 9, 4, 4, 9, 3, 9, 3, 9, 8,
       9, 3, 7, 4, 3, 3, 3, 3, 0, 0, 7, 2])

In [51]:
pred_classes_one_hot = np.zeros((100,10))
pred_classes_one_hot[np.arange(100), pred_classes] = 1
pred_classes_one_hot


array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 

In [52]:
labels

array([7, 0, 3, 7, 5, 7, 7, 0, 6, 8, 3, 3, 6, 1, 7, 0, 7, 3, 5, 5, 7, 2,
       1, 5, 9, 4, 1, 5, 6, 0, 7, 3, 0, 0, 9, 4, 2, 0, 3, 1, 4, 2, 2, 3,
       6, 0, 3, 8, 3, 2, 0, 7, 8, 6, 9, 9, 7, 4, 1, 6, 6, 0, 2, 1, 0, 9,
       4, 5, 5, 6, 2, 5, 5, 1, 4, 8, 4, 3, 2, 3, 2, 7, 7, 1, 9, 8, 3, 7,
       1, 3, 7, 1, 6, 1, 6, 5, 0, 3, 4, 3], dtype=int32)

In [53]:
out = pred_classes_one_hot
out

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 

In [54]:
probs = out[np.arange(100), labels]
loss = -np.mean(np.log(probs + 1e-9))
loss

np.float64(17.822008619633912)

## f) calculate accuracy, precision, recall, f1 score

In [55]:
pred_classes, labels

(array([1, 2, 9, 7, 4, 4, 4, 4, 4, 8, 9, 9, 8, 4, 5, 8, 9, 9, 3, 4, 4, 2,
        3, 1, 4, 3, 3, 0, 2, 9, 3, 2, 3, 8, 9, 7, 9, 6, 3, 2, 9, 6, 2, 0,
        6, 2, 9, 4, 3, 9, 9, 0, 4, 0, 9, 9, 4, 3, 4, 3, 3, 3, 4, 3, 3, 8,
        8, 9, 0, 4, 9, 6, 8, 6, 9, 0, 8, 9, 3, 9, 4, 4, 9, 3, 9, 3, 9, 8,
        9, 3, 7, 4, 3, 3, 3, 3, 0, 0, 7, 2]),
 array([7, 0, 3, 7, 5, 7, 7, 0, 6, 8, 3, 3, 6, 1, 7, 0, 7, 3, 5, 5, 7, 2,
        1, 5, 9, 4, 1, 5, 6, 0, 7, 3, 0, 0, 9, 4, 2, 0, 3, 1, 4, 2, 2, 3,
        6, 0, 3, 8, 3, 2, 0, 7, 8, 6, 9, 9, 7, 4, 1, 6, 6, 0, 2, 1, 0, 9,
        4, 5, 5, 6, 2, 5, 5, 1, 4, 8, 4, 3, 2, 3, 2, 7, 7, 1, 9, 8, 3, 7,
        1, 3, 7, 1, 6, 1, 6, 5, 0, 3, 4, 3], dtype=int32))

In [56]:
accuracy = np.mean(pred_classes == labels)
accuracy


np.float64(0.14)

In [57]:
classes = np.unique(labels)
classes

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [58]:
precision_list = []
recall_list = []
f1_list = []

for c in classes:
    tp = np.sum((pred_classes == c) & (labels == c))
    fp = np.sum((pred_classes == c) & (labels != c))
    fn = np.sum((pred_classes != c) & (labels == c))
    
    precision = tp / (tp + fp + 1e-9)
    recall = tp / (tp + fn + 1e-9)
    f1 = 2 * precision * recall / (precision + recall + 1e-9)
    
    precision_list.append(precision)
    recall_list.append(recall)
    f1_list.append(f1)

In [59]:
precision_list

[np.float64(0.124999999984375),
 np.float64(0.0),
 np.float64(0.24999999996875),
 np.float64(0.136363636357438),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.19999999996),
 np.float64(0.499999999875),
 np.float64(0.11111111109876542),
 np.float64(0.17391304347069944)]

In [60]:
precision = np.mean(precision_list)
recall = np.mean(recall_list)
f1_score = np.mean(f1_list)

In [61]:
print("Precision score ", precision)
print("recall score : ", recall)
print("f1 score ", f1_score)

Precision score  0.14963877907150278
recall score :  0.16150793648630807
f1 score  0.12717310440212257
