### generate the dataset

In [82]:
import torch

In [132]:
marks = torch.zeros(80, 6, dtype=torch.long)
marks

tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0,

In [133]:

choice = torch.randint(0, 3, (80,6))
marks[choice == 0] = torch.randint(1, 41, ((choice == 0).sum(),))
marks[choice == 1] = torch.randint(41, 71, ((choice == 1).sum(),))
marks[choice == 2] = torch.randint(71, 96, ((choice == 2).sum(),))

In [134]:
marks = marks.float()
marks

tensor([[30., 59., 69., 82., 67., 61.],
        [94., 95., 94., 59.,  7., 57.],
        [63., 51., 65., 94., 47., 47.],
        [52., 84., 89., 19., 92., 42.],
        [52., 50., 91., 40., 51., 27.],
        [48., 79., 90., 63., 51., 59.],
        [79., 49., 85., 82., 55., 72.],
        [48.,  8., 34., 26., 31., 79.],
        [58., 78., 46.,  9., 32., 55.],
        [90., 65., 76., 71., 30., 46.],
        [42., 63., 81., 70., 48., 38.],
        [74., 16., 75., 95., 57., 82.],
        [25., 75., 38., 21., 55., 38.],
        [14., 67., 64., 57., 41., 55.],
        [61., 41., 67., 79., 40., 48.],
        [89., 83., 93., 33., 86., 82.],
        [19., 56., 33., 10., 66., 28.],
        [59., 62., 90.,  9., 42., 37.],
        [27., 67., 27., 90., 31., 46.],
        [64., 74., 72., 88., 12., 83.],
        [88., 82.,  8., 71., 48., 88.],
        [37., 76., 84., 61., 41., 65.],
        [57., 76., 83., 94., 37., 48.],
        [72., 71., 60., 23., 63., 83.],
        [46., 85., 57.,  5., 88., 85.],


### test train split

In [135]:
train = marks[:56]
valid = marks[56:68]
test = marks[68:80]

train.shape, valid.shape, test.shape

(torch.Size([56, 6]), torch.Size([12, 6]), torch.Size([12, 6]))

In [136]:
X_train = train[:, :5]  
y_train = train[:, 5].view(-1,1)
X_valid = valid[:, :5]  
y_valid = valid[:, 5].view(-1,1)
X_test = test[:, :5]  
y_test = test[:, 5].view(-1,1)
mean = X_train.mean(dim=0)
std = X_train.std(dim=0)
X_train = (X_train - mean) / std
X_valid = (X_valid - mean) / std
X_test = (X_test - mean) / std
X_train.shape, y_train.shape, X_valid.shape, y_valid.shape, X_test.shape, y_test.shape

(torch.Size([56, 5]),
 torch.Size([56, 1]),
 torch.Size([12, 5]),
 torch.Size([12, 1]),
 torch.Size([12, 5]),
 torch.Size([12, 1]))

### y = 3m1 + 3.5m2 + 4.5m3 + 5.1m4 + 6.5m5 of row(0,1)

In [148]:
X_train

tensor([[-0.7693,  0.1216,  0.4093,  0.8854,  0.7583],
        [ 1.6220,  1.5225,  1.3955,  0.1312, -1.7897],
        [ 0.4637, -0.1897,  0.2515,  1.2789, -0.0910],
        [ 0.0527,  1.0945,  1.1982, -1.1805,  1.8200],
        [ 0.0527, -0.2286,  1.2771, -0.4919,  0.0789],
        [-0.0967,  0.8999,  1.2377,  0.2623,  0.0789],
        [ 1.0615, -0.2675,  1.0405,  0.8854,  0.2487],
        [-0.0967, -1.8630, -0.9714, -0.9510, -0.7705],
        [ 0.2769,  0.8610, -0.4980, -1.5084, -0.7280],
        [ 1.4725,  0.3551,  0.6854,  0.5247, -0.8129],
        [-0.3209,  0.2773,  0.8827,  0.4919, -0.0485],
        [ 0.8747, -1.5517,  0.6460,  1.3117,  0.3337],
        [-0.9561,  0.7442, -0.8136, -1.1149,  0.2487],
        [-1.3671,  0.4329,  0.2120,  0.0656, -0.3458],
        [ 0.3890, -0.5788,  0.3304,  0.7870, -0.3883],
        [ 1.4352,  1.0555,  1.3560, -0.7214,  1.5652],
        [-1.1803,  0.0049, -1.0109, -1.4756,  0.7159],
        [ 0.3143,  0.2383,  1.2377, -1.5084, -0.3033],
        [-

In [150]:
W = torch.tensor([[0.0],
                  [0.0],
                  [0.0],
                  [0.0],
                  [0.0]])
b = torch.tensor([0.0])

In [151]:
y_pred = X_train @ W 

In [113]:
y_pred

tensor([[  1.2183],
        [-36.3415],
        [ -9.1080],
        [ 20.0888],
        [  5.2031],
        [ 21.7696],
        [ 21.8970],
        [-26.4692],
        [-14.3358],
        [ -6.5686],
        [  4.5335],
        [  5.1582],
        [-19.9399],
        [  5.1168],
        [ -7.7481],
        [-18.7777],
        [ -3.0076],
        [ -0.9781],
        [-35.1496],
        [ -9.7454],
        [-20.3401],
        [ 13.3192],
        [-31.6918],
        [  6.4570],
        [ 28.3006],
        [ 28.3063],
        [ -3.6534],
        [  2.7431],
        [-17.8743],
        [ 18.7074],
        [ 19.4705],
        [  7.8612],
        [ -6.4757],
        [ 10.1378],
        [  2.6765],
        [ 31.3873],
        [ -3.1526],
        [ -0.6603],
        [-12.0932],
        [ -2.3407],
        [ 14.4116],
        [-16.3914],
        [  7.1702],
        [ -7.2958],
        [  0.2500],
        [ 28.8995],
        [  3.2594],
        [  1.7975],
        [ -8.2137],
        [-20.9916],


In [152]:
loss = torch.mean((y_pred - y_train)**2)
print(loss)

tensor(3837.8035)


In [144]:
y_pred1 = X_valid @ W 
loss1 = torch.mean((y_pred1 - y_valid)**2)
print(loss1)

tensor(3978.0833)


#### do manual backpropagation

L = 1/n  (y_pred-y)**2 , dL/dy = 2/n (y_pred-y)

dL/dW = X` dL/dy

dL/db = (sum)dL/dy_pred

In [153]:
lr = 0.01
for epoch in range(1000):
     y_pred = X_train @ W + b
     loss = torch.mean((y_pred - y_train)**2)
     n = X_train.shape[0]
     error = y_pred - y_train

     dL_dy = (2/n) * error
     dW = X_train.T @ dL_dy
     db = torch.sum(dL_dy)

     W = W - lr * dW
     b = b - lr * db

     if epoch % 100 == 0:
        print(epoch, loss.item())

0 3837.803466796875
100 615.3817749023438
200 557.3782958984375
300 556.2777099609375
400 556.253662109375
500 556.2529907226562
600 556.2529907226562
700 556.2529907226562
800 556.2529907226562
900 556.2529907226562


In [146]:

y_valid_pred = X_valid @ W + b
valid_loss = torch.mean((y_valid_pred - y_valid)**2)
print(f"Validation Loss: {valid_loss.item():.4f}")

Validation Loss: 581.9406


In [147]:

y_test_pred = X_test @ W + b
test_loss = torch.mean((y_test_pred - y_test)**2)
print(f"Test Loss: {test_loss.item():.4f}")

Test Loss: 907.0888


In [107]:
W

tensor([[-0.2958],
        [-3.5820],
        [-1.1898],
        [-1.5532],
        [-2.5978]])